-- 008: WireGuard management tunnel per router
-- Routers behind CGNAT have no reachable public IP, so server->router traffic
-- (ICMP heartbeat, RFC 5176 CoA/Disconnect, later RADIUS itself) needs a
-- router-initiated tunnel. Each device gets a keypair (generated by the API,
-- delivered inside the setup script) and a tunnel IP in 10.77.0.0/16; the
-- host cron scripts/wg-sync.sh reconciles wg0 peers with this table.

ALTER TABLE devices
    ADD COLUMN IF NOT EXISTS wg_private_key TEXT,
    ADD COLUMN IF NOT EXISTS wg_public_key TEXT,
    ADD COLUMN IF NOT EXISTS wg_ip INET UNIQUE;

-- 10.77.0.1 is the server; device IPs start at 10.77.0.10
CREATE SEQUENCE IF NOT EXISTS wg_ip_seq START 10;
